name=Vira Matrix Library
version=1.0.0
author=Mostafa Mir Mosavi (ViraMedar)
maintainer=Mostafa Mir Mosavi
sentence=Advanced 8x8 LED Matrix library for ESP8266/ESP32 using 74HC595 shift register with WebSocket control, animations, and web UI.
paragraph=Vira Matrix Library is a powerful Arduino library designed for controlling 8x8 LED matrix displays using the 74HC595 shift register. It includes emoji animation engine, scrolling text system, built-in 5x7 font, and real-time WebSocket communication. The library is optimized for ESP8266 and ESP32 microcontrollers and supports web-based drawing interface and IoT applications. Designed and developed by Mostafa Mir Mosavi (known as ViraMedar / Vira / ViraEP / ViraMedar Team). This project is part of the Vira Embedded Systems ecosystem and is used for smart display, IoT dashboards, and LED animation systems.
category=Display
url=https://github.com/admin3314/Vira_Matrix_Library
architectures=esp8266,esp32
includes=Vira_Matrix.h
