name=Vira_Matrix_Display
version=1.0.1
author=Mostafa Mir Mosavi (@viramedar)
maintainer=Mostafa Mir Mosavi (@viramedar)
sentence=Advanced 8x8 LED Matrix Display with Emoji, Font and Web Control for ESP8266.
paragraph=Vira_Matrix_Display is a lightweight and powerful Arduino library for controlling 8x8 LED matrix displays. It supports emoji animations, 5x7 font rendering, scrolling text, and real-time WebSocket control via ESP8266 web interface. Designed for fast performance and future scalability.
category=Display
url=https://github.com/admin3314/Vira_Matrix_Display
architectures=esp8266,esp32
includes=Vira_Matrix.h
